repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
        always_run: true
      - id: trailing-whitespace
        always_run: true
      - id: check-json
        always_run: true
      - id: check-added-large-files
        always_run: true
      - id: check-yaml
        always_run: true
      - id: check-merge-conflict
        always_run: true
        args: ["--assume-in-merge"]
      - id: debug-statements
        always_run: true
      - id: name-tests-test
        always_run: true
      - id: requirements-txt-fixer
        always_run: true
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: '\.bat|\.csv|\.ps1$'
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports
  # isort conflict with black
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.9.3
  #   hooks:
  #     - id: isort
  #       always_run: true
  #       name: isort (python)
  #       args: ["--settings-path .isort.cfg"]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        always_run: true

  # skip flake8 and mypy for now

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
  #       always_run: true
  #       args: ["--config=packages/syft/setup.cfg"]
  #       #       additional_dependencies:
  #       #         - flake8-kwarger
  #       #         - darglint

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.910
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       always_run: true
  #       files: ^
  #       args: [
  #           "--ignore-missing-imports",
  #           "--scripts-are-modules",
  #           "--disallow-incomplete-defs",
  #           "--no-implicit-optional",
  #           "--warn-unused-ignores",
  #           "--warn-redundant-casts",
  #           "--strict-equality",
  #           "--warn-unreachable",
  #           # "--disallow-untyped-decorators",
  #           "--disallow-untyped-defs",
  #           "--disallow-untyped-calls",
  #           "--namespace-packages",
  #           "--install-types",
  #           "--non-interactive",
  #         ]